### ISSUE TITLE
TypeScript type issue on domAttributes from immer

### ISSUE THREAD

**Issue by seeshinghei** [xyflow/xyflow#5470]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.8.3
- Browser and version: Google Chrome 137.0.7151.104 (x86_64)
- OS and version: macOS Sequoia 15.5

### Live code example

https://codesandbox.io/p/devbox/r2724j?file=%2Fsrc%2FReducers.ts%3A15%2C25

### Describe the Bug

After upgrade from 12.6.4 to 12.8.3, we see TypeScript type issue related to domAttributes. The type issues seems to be brought out by the @types/trusted-types or dompurify libraries. See live code sample for details.

TS error:
```
src/Reducers.ts:15:12 - error TS2345: Argument of type 'WritableDraft<Edge>[]' is not assignable to parameter of type 'Edge[]'.
  Type 'WritableDraft<Edge>' is not assignable to type 'Edge'.
    Type 'WritableDraft<Edge>' is not assignable to type '{ style?: CSSProperties | undefined; className?: string | undefined; reconnectable?: boolean | HandleType | undefined; focusable?: boolean | undefined; ariaRole?: AriaRole | undefined; domAttributes?: Omit<...> | undefined; }'.
      Types of property 'domAttributes' are incompatible.
        Type 'WritableDraft<Omit<SVGAttributes<SVGGElement>, "id" | "className" | "style" | "role" | "aria-label">> | undefined' is not assignable to type 'Omit<SVGAttributes<SVGGElement>, "id" | "className" | "style" | "role" | "aria-label"> | undefined'.
          Type 'WritableDraft<Omit<SVGAttributes<SVGGElement>, "id" | "className" | "style" | "role" | "aria-label">>' is not assignable to type 'Omit<SVGAttributes<SVGGElement>, "id" | "className" | "style" | "role" | "aria-label">'.
            Types of property 'dangerouslySetInnerHTML' are incompatible.
              Type 'WritableDraft<{ __html: string | TrustedHTML; }> | undefined' is not assignable to type '{ __html: string | TrustedHTML; } | undefined'.
                Type 'WritableDraft<{ __html: string | TrustedHTML; }>' is not assignable to type '{ __html: string | TrustedHTML; }'.
                  Types of property '__html' are incompatible.
                    Type 'string | WritableDraft<TrustedHTML>' is not assignable to type 'string | TrustedHTML'.
                      Type 'WritableDraft<TrustedHTML>' is not assignable to type 'string | TrustedHTML'.
```

### Steps to reproduce the bug or issue

1. Install @types/trusted-types or dompurify
2. Install @xyflow/react@12.8.3
3. Create a helper function that accepts a plain array of Edge[]
4. Create a RTK slice with a reducer that calls the helper function

### Expected behavior

As a user, I expect there is no TS type issue when using xyflow with immer / RTK

**Comment by moklick** [comment]
I love those TS error messages :D  Thanks for the report we will have a look!

**Comment by moklick** [comment]
should be fixed in 12.8.4
