### ISSUE TITLE
@xyflow/react ^12.5.0 - Promise.withResolvers is not a function

### ISSUE THREAD

**Issue by PhilBroadbent** [xyflow/xyflow#5210]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.5.5 (commit exists since 12.5.0, see below)
- Browser and version: Node v20.19
- OS and version: MacOS Sequoia

### Describe the Bug

`Promise.withResolvers` is being used, introduced in https://github.com/xyflow/xyflow/commit/f208223400f725dcd1dfac98dc9800e8a9bd38bd#diff-1fc4858c0ec0e48d0de0b5c2463e43b1d0b20671d30d4a330524f686005495fbR283, but this isn't supported in Node v20 so throws an exception when running tests 

### Steps to reproduce the bug or issue

1. Change to Node V20
2. Run test targeting @xyflow/react's fitView
3. See exception `TypeError: Promise.withResolvers is not a function`

### Expected behavior

Node v20 is still in maintenance, so should be supported here I believe

**Comment by peterkogo** [comment]
Can't have nice things in webdev, can we.. Thanks for reporting this! We were pondering if using a new javascript feature might be problematic and it seems so! 🥲

**Comment by moklick** [comment]
fixed in 12.5.6
